apiVersion: v1
kind: Service
metadata:
  name: project-one-service
spec:
  selector:
    app.kubernetes.io/name: project-one
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: NodePort
